backend:
  name: github
  repo: tonusername/tonrepo # عدلي باسم المستخدم واسم Repo
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "content/actualites"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "liste_principale"
    label: "Liste principale"
    folder: "content/liste_principale"
    create: true
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Prénom", name: "prenom", widget: "string" }
      - { label: "Fonction", name: "fonction", widget: "string" }

  - name: "loi_fondamentale"
    label: "Loi fondamentale"
    folder: "content/loi_fondamentale"
    create: true
    fields:
      - { label: "Article", name: "article", widget: "string" }
      - { label: "Texte", name: "texte", widget: "text" }
